---
# Original https://github.com/helm/charts/blob/master/stable/minio/values.yaml
replicas: 1
ingress:
  enabled: false
buckets: []
  #- name: tf-state-files
  #  policy: none
  #  purge: false
metrics:
  # Metrics can not be disabled yet: https://github.com/minio/minio/issues/7493
  serviceMonitor:
    enabled: false
environment:
  MINIO_PROMETHEUS_AUTH_TYPE: "public"